/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        surface: 'hsl(var(--surface))',
        'surface-raised': 'hsl(var(--surface-raised))',
        'surface-overlay': 'hsl(var(--surface-overlay))',
        brand: 'hsl(var(--brand))',
        'brand-foreground': 'hsl(var(--brand-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        success: 'hsl(var(--success))',
        'success-foreground': 'hsl(var(--success-foreground))',
        danger: 'hsl(var(--danger))',
        'danger-foreground': 'hsl(var(--danger-foreground))',
        warning: 'hsl(var(--warning))',
        'warning-foreground': 'hsl(var(--warning-foreground))',
        foreground: 'hsl(var(--foreground))',
        muted: 'hsl(var(--muted))',
        subtle: 'hsl(var(--subtle))',
        border: 'hsl(var(--border))',
        'border-strong': 'hsl(var(--border-strong))',
        'card-action': 'hsl(var(--card-action))',
        'card-group': 'hsl(var(--card-group))',
        'card-game': 'hsl(var(--card-game))',
        'card-reflex': 'hsl(var(--card-reflex))',
        'card-showdown': 'hsl(var(--card-showdown))',
        'card-modifier': 'hsl(var(--card-modifier))',
        'card-benefit': 'hsl(var(--card-benefit))',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        syne: ['Syne', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
    },
  },
  plugins: [],
}
